### ISSUE TITLE
OID-V6 dataset preprocessing

### ISSUE THREAD

**Issue by Leterax** [Alibaba-MIIL/PartialLabelingCSL#1]
Amazing paper, especially so soon after the last one, great work!
I had one question regarding the oidv6 dataset: did you do any preprocessing to filter out bad classes etc? How many of the 9 million images did you end up using? Also, are there any large differeneces between train.py (COCO) and what you used to train on the oidv6 dataset?

Thanks in advance.

**Comment by HITESHLPATEL** [comment]
Hey, @ebenbaruch  Thanks for sharing your great work. I have a question regarding training on OpenImages. Did you use Negative annotations during training for eg each image comes with a label and confidence of 0 and 1? So did only take positive annotations i.e Label with confidence 1?

**Comment by ebenbaruch** [comment]
Yes, we used the negative annotations as well. Each sample is annotated with a few positive labels and a few negative labels. The rest of the labels are unknown.

**Comment by HITESHLPATEL** [comment]
Thanks, @ebenbaruch . Currently how I train is I use only positive labels I,e the one with Confidence 1, and create a one-hot encoding for the image i.e [0,0,1,0....n9605] and train the model. What changes do I need to do if I also want to incorporate negative labels during training? Thank you

**Comment by ebenbaruch** [comment]
The approach you mentioned refers to the "negative" mode. If you like to consider also the annotated negative labels, you can use the baseline training mode: --partial_loss_mode=ignore, or our method: --partial_loss_mode=selective. You may want to look at the PartialSelectiveLoss for more details: (https://github.com/Alibaba-MIIL/PartialLabelingCSL/blob/534f3ce1997607ceaa2db8eb5d06986f490ed88b/src/loss_functions/partial_asymmetric_loss.py#L71).
