### ISSUE TITLE
How can I apply it to custom dataset?

### ISSUE THREAD

**Issue by wasdzzzzzz** [Alibaba-MIIL/PartialLabelingCSL#11]
--prior_path=./outputs/priors/prior_fpc_1000.csv
How can I get prior_fpc_1000.csv for my own dataset？
Thanks a lot in advance.

**Comment by gordonjun2** [comment]
Hi there. I tested it with my own dataset already. To get the 'prior_fpc_1000.csv' for your own dataset, you need to run the train.py without it first (set your 'args.prior_path' to be None). The prior will be generated throughout the training. There are some information in the paper (eg. using 'Ignore' mode for your 'args.partial_loss_mode' for the first training).

**Comment by wasdzzzzzz** [comment]
> Hi there. I tested it with my own dataset already. To get the 'prior_fpc_1000.csv' for your own dataset, you need to run the train.py without it first (set your 'args.prior_path' to be None). The prior will be generated throughout the training. There are some information in the paper (eg. using 'Ignore' mode for your 'args.partial_loss_mode' for the first training).

Thank you very much for your reply~
